"use client";
import { useCallback, useEffect, useState } from "react";

const statuses: Record<string,string>={QUEUED:"En espera",RUNNING:"Leyendo la tienda",PENDING_DEPLOY:"Pendiente de actualizar el blog",DEPLOYING:"Actualizando el blog",COMPLETED:"Actualizado",PARTIAL:"Actualizado con alertas",FAILED:"No se pudo completar"};
type Run={id:string;status:string;startedAt:string;progress:{read:number;total:number};changes:Array<{kind:string;ref:string;action:string;name:string;beforeUrl:string;afterUrl:string;candidates?:string[];incoming?:unknown}>;errors:Array<{url?:string;error:string}>;deployment:{verified?:boolean;skipped?:boolean;error?:string};deploymentAttempts:number};
type Candidate={id:string;name:string;linkStatus:string;externalId?:string;key?:string};
type State={config:{enabled:boolean};runs:Run[];products:Candidate[];categories:Candidate[]};
export function CatalogSyncPanel({clientId}:{clientId:string}){
  const [state,setState]=useState<State>(),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>{try{const r=await fetch(`/api/blog/catalog/sync?clientId=${encodeURIComponent(clientId)}`,{cache:"no-store"});const data=await r.json();if(!r.ok)throw new Error(data.error);setState(data);}catch(e){setMessage(e instanceof Error?e.message:"No se pudo consultar el catálogo. Reintentá en unos minutos.");}},[clientId]);
  useEffect(()=>{void refresh();const timer=setInterval(()=>{void refresh();},15_000);return()=>clearInterval(timer);},[refresh]);
  async function act(action:string,extra:Record<string,unknown>={}){setBusy(true);setMessage("");try{const r=await fetch("/api/blog/catalog/sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientId,action,...extra})});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessage(action==="configure"?"Configuración guardada.":"La tarea quedó en espera. El trabajador local la ejecutará automáticamente.");await refresh();}catch(e){setMessage(e instanceof Error?e.message:"No se pudo iniciar. Reintentá en unos minutos.");}finally{setBusy(false);}}
  const run=state?.runs[0],active=run&&["QUEUED","RUNNING","DEPLOYING"].includes(run.status);
  const removed=[...(state?.products||[]),...(state?.categories||[])].filter(p=>p.linkStatus==="missing");
  return <section className="mt-8 rounded-xl border border-ink/10 bg-paper p-6 shadow-sm">
    <h2 className="font-display text-xl font-semibold text-ink">Catálogo de Tiendanube</h2>
    <p className="mt-2 text-sm text-slate">Lee productos y categorías públicos cada día a las 06:00, hora de Buenos Aires. Actualiza los enlaces del blog y conserva los textos revisados. Requiere el trabajador local encendido.</p>
    <div className="mt-4 flex flex-wrap items-center gap-4">
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={state?.config.enabled||false} disabled={!state||busy} onChange={e=>void act("configure",{enabled:e.target.checked})}/>Sincronizar diariamente</label>
      <button type="button" disabled={busy||Boolean(active)} onClick={()=>void act("sync")} className="rounded-lg bg-ink px-4 py-2 text-sm text-paper disabled:opacity-50">Sincronizar ahora</button>
      {run&&["PENDING_DEPLOY","FAILED"].includes(run.status)?<button type="button" disabled={busy} onClick={()=>void act("retry",{runId:run.id})} className="rounded-lg border border-ink/20 px-4 py-2 text-sm">Reintentar actualización</button>:null}
    </div>
    <p className="mt-3 text-sm" role="status">{message}</p>
    {run?<div className="mt-4 text-sm"><p className="font-semibold">{statuses[run.status]||run.status} · {new Date(run.startedAt).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires"})}</p><p className="mt-1 text-slate">{run.progress.read} de {run.progress.total} páginas leídas · {run.changes.filter(c=>c.action==="create").length} altas · {run.changes.filter(c=>c.action==="update").length} actualizaciones</p>{run.deployment.verified?<p className="mt-1 text-moss">{run.deployment.skipped?"El blog no necesitó cambios.":"Actualización del blog verificada."}</p>:null}{run.deployment.error?<p className="mt-2 text-rose-700">{run.deployment.error}</p>:null}
      {run.changes.some(c=>c.action==="review"&&c.incoming)?<div className="mt-4"><h3 className="font-semibold">Vinculaciones para revisar</h3>{run.changes.filter(c=>c.action==="review"&&c.incoming).map(c=><div key={c.ref} className="mt-2 rounded-lg border border-ink/10 p-3"><p>{c.name}</p><select aria-label={`Vincular ${c.name}`} defaultValue="" disabled={busy} onChange={e=>{if(e.target.value)void act("resolve",{runId:run.id,ref:c.ref,targetId:e.target.value});}} className="mt-2 w-full rounded border border-ink/20 p-2"><option value="">Elegir el registro existente</option>{(c.kind==="product"?state?.products:state?.categories)?.filter(p=>c.candidates?.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name} · {p.externalId||p.key}</option>)}</select></div>)}</div>:null}
      {run.changes.some(c=>c.beforeUrl&&c.beforeUrl!==c.afterUrl)?<details className="mt-4"><summary>Ver cambios de enlaces</summary><ul className="mt-2 space-y-3">{run.changes.filter(c=>c.beforeUrl&&c.beforeUrl!==c.afterUrl).map(c=><li key={`${c.kind}:${c.ref}`}><p className="font-semibold">{c.name}</p><p className="break-all text-xs text-slate">Antes: {c.beforeUrl}</p><p className="break-all text-xs text-slate">Ahora: {c.afterUrl||"Texto sin enlace"}</p></li>)}</ul></details>:null}
      {run.errors.length?<details className="mt-4"><summary>{run.errors.length} páginas requieren revisión</summary><ul className="mt-2 space-y-2">{run.errors.slice(0,30).map((e,i)=><li key={i} className="break-words text-xs">{e.error}</li>)}</ul></details>:null}
    </div>:<p className="mt-4 text-sm text-slate">Todavía no hay sincronizaciones. Activá el ciclo diario o seleccioná “Sincronizar ahora”.</p>}
    {removed.length?<details className="mt-4 text-sm"><summary>{removed.length} fichas retiradas: sus menciones se muestran sin enlace</summary><ul className="mt-2 list-inside list-disc">{removed.map(p=><li key={p.id}>{p.name}</li>)}</ul></details>:null}
    {state&&state.runs.length>1?<details className="mt-4 text-sm"><summary>Historial reciente</summary><ul className="mt-2 space-y-1">{state.runs.slice(1).map(r=><li key={r.id}>{new Date(r.startedAt).toLocaleString("es-AR",{timeZone:"America/Argentina/Buenos_Aires"})} · {statuses[r.status]||r.status}</li>)}</ul></details>:null}
  </section>;
}
